/**
 * Single Supabase client for the whole app.
 *
 * The client itself is generated by the backend integration
 * (`@/integrations/supabase/client`) and reads its URL/key from the project
 * environment. Re-exporting it here keeps every existing
 * `import { supabase } from '@/lib/supabase'` working while guaranteeing there
 * is exactly ONE client instance — two clients would each keep their own auth
 * session in localStorage and silently log the user out on refresh.
 */
export { supabase } from '@/integrations/supabase/client';
