/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NovoRouteImport } from './routes/novo'
import { Route as JornadaRouteImport } from './routes/jornada'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as CronogramaRouteImport } from './routes/cronograma'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesIndexRouteImport } from './routes/configuracoes.index'
import { Route as ConfiguracoesPrivacidadeRouteImport } from './routes/configuracoes.privacidade'
import { Route as ConfiguracoesPerfilRouteImport } from './routes/configuracoes.perfil'
import { Route as ConfiguracoesNotificacoesRouteImport } from './routes/configuracoes.notificacoes'

const NovoRoute = NovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaRoute = JornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const CronogramaRoute = CronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesIndexRoute = ConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesPrivacidadeRoute =
  ConfiguracoesPrivacidadeRouteImport.update({
    id: '/privacidade',
    path: '/privacidade',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ConfiguracoesPerfilRoute = ConfiguracoesPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesNotificacoesRoute =
  ConfiguracoesNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compras': typeof ComprasRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/cronograma': typeof CronogramaRoute
  '/documentos': typeof DocumentosRoute
  '/entrar': typeof EntrarRoute
  '/financeiro': typeof FinanceiroRoute
  '/jornada': typeof JornadaRoute
  '/novo': typeof NovoRoute
  '/configuracoes/notificacoes': typeof ConfiguracoesNotificacoesRoute
  '/configuracoes/perfil': typeof ConfiguracoesPerfilRoute
  '/configuracoes/privacidade': typeof ConfiguracoesPrivacidadeRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compras': typeof ComprasRoute
  '/cronograma': typeof CronogramaRoute
  '/documentos': typeof DocumentosRoute
  '/entrar': typeof EntrarRoute
  '/financeiro': typeof FinanceiroRoute
  '/jornada': typeof JornadaRoute
  '/novo': typeof NovoRoute
  '/configuracoes/notificacoes': typeof ConfiguracoesNotificacoesRoute
  '/configuracoes/perfil': typeof ConfiguracoesPerfilRoute
  '/configuracoes/privacidade': typeof ConfiguracoesPrivacidadeRoute
  '/configuracoes': typeof ConfiguracoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compras': typeof ComprasRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/cronograma': typeof CronogramaRoute
  '/documentos': typeof DocumentosRoute
  '/entrar': typeof EntrarRoute
  '/financeiro': typeof FinanceiroRoute
  '/jornada': typeof JornadaRoute
  '/novo': typeof NovoRoute
  '/configuracoes/notificacoes': typeof ConfiguracoesNotificacoesRoute
  '/configuracoes/perfil': typeof ConfiguracoesPerfilRoute
  '/configuracoes/privacidade': typeof ConfiguracoesPrivacidadeRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compras'
    | '/configuracoes'
    | '/cronograma'
    | '/documentos'
    | '/entrar'
    | '/financeiro'
    | '/jornada'
    | '/novo'
    | '/configuracoes/notificacoes'
    | '/configuracoes/perfil'
    | '/configuracoes/privacidade'
    | '/configuracoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compras'
    | '/cronograma'
    | '/documentos'
    | '/entrar'
    | '/financeiro'
    | '/jornada'
    | '/novo'
    | '/configuracoes/notificacoes'
    | '/configuracoes/perfil'
    | '/configuracoes/privacidade'
    | '/configuracoes'
  id:
    | '__root__'
    | '/'
    | '/compras'
    | '/configuracoes'
    | '/cronograma'
    | '/documentos'
    | '/entrar'
    | '/financeiro'
    | '/jornada'
    | '/novo'
    | '/configuracoes/notificacoes'
    | '/configuracoes/perfil'
    | '/configuracoes/privacidade'
    | '/configuracoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComprasRoute: typeof ComprasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  CronogramaRoute: typeof CronogramaRoute
  DocumentosRoute: typeof DocumentosRoute
  EntrarRoute: typeof EntrarRoute
  FinanceiroRoute: typeof FinanceiroRoute
  JornadaRoute: typeof JornadaRoute
  NovoRoute: typeof NovoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/novo': {
      id: '/novo'
      path: '/novo'
      fullPath: '/novo'
      preLoaderRoute: typeof NovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada': {
      id: '/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof JornadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronograma': {
      id: '/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof CronogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/': {
      id: '/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof ConfiguracoesIndexRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/privacidade': {
      id: '/configuracoes/privacidade'
      path: '/privacidade'
      fullPath: '/configuracoes/privacidade'
      preLoaderRoute: typeof ConfiguracoesPrivacidadeRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/perfil': {
      id: '/configuracoes/perfil'
      path: '/perfil'
      fullPath: '/configuracoes/perfil'
      preLoaderRoute: typeof ConfiguracoesPerfilRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/notificacoes': {
      id: '/configuracoes/notificacoes'
      path: '/notificacoes'
      fullPath: '/configuracoes/notificacoes'
      preLoaderRoute: typeof ConfiguracoesNotificacoesRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
  }
}

interface ConfiguracoesRouteChildren {
  ConfiguracoesNotificacoesRoute: typeof ConfiguracoesNotificacoesRoute
  ConfiguracoesPerfilRoute: typeof ConfiguracoesPerfilRoute
  ConfiguracoesPrivacidadeRoute: typeof ConfiguracoesPrivacidadeRoute
  ConfiguracoesIndexRoute: typeof ConfiguracoesIndexRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesNotificacoesRoute: ConfiguracoesNotificacoesRoute,
  ConfiguracoesPerfilRoute: ConfiguracoesPerfilRoute,
  ConfiguracoesPrivacidadeRoute: ConfiguracoesPrivacidadeRoute,
  ConfiguracoesIndexRoute: ConfiguracoesIndexRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComprasRoute: ComprasRoute,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  CronogramaRoute: CronogramaRoute,
  DocumentosRoute: DocumentosRoute,
  EntrarRoute: EntrarRoute,
  FinanceiroRoute: FinanceiroRoute,
  JornadaRoute: JornadaRoute,
  NovoRoute: NovoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
